"""init videos

Revision ID: 17baf22a7d30
Revises: 
Create Date: 2025-12-18 18:30:27.148040

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17baf22a7d30'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('videos',
    sa.Column('video_created_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('views_count', sa.BigInteger(), nullable=False),
    sa.Column('likes_count', sa.BigInteger(), nullable=False),
    sa.Column('reports_count', sa.BigInteger(), nullable=False),
    sa.Column('comments_count', sa.BigInteger(), nullable=False),
    sa.Column('creator_id', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('video_snapshots',
    sa.Column('video_id', sa.UUID(), nullable=False),
    sa.Column('views_count', sa.BigInteger(), nullable=False),
    sa.Column('likes_count', sa.BigInteger(), nullable=False),
    sa.Column('reports_count', sa.BigInteger(), nullable=False),
    sa.Column('comments_count', sa.BigInteger(), nullable=False),
    sa.Column('delta_views_count', sa.BigInteger(), nullable=False),
    sa.Column('delta_likes_count', sa.BigInteger(), nullable=False),
    sa.Column('delta_reports_count', sa.BigInteger(), nullable=False),
    sa.Column('delta_comments_count', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_snapshots')
    op.drop_table('videos')
    # ### end Alembic commands ###
